from typing import List, Union, Literal, Dict, get_args

AllowedSuggestionType = Union[Literal['position'], Literal['strength'], Literal['stability'], Literal['racket'],
Literal['others']]

AllowedSuggestionKey = Union[Literal['center_of_gravity'],
Literal["right_wrist"], Literal["right_shoulder"],
Literal["right_forearm"], Literal['time_of_striking_ball'],
Literal["angle_of_racket"], Literal['left_foot'], Literal['right_foot'], Literal['waist'],
Literal["right_upper_arm"],
Literal["left_shoulder"], Literal["left_elbow"], Literal["right_elbow"],
Literal["left_wrist"],
Literal["backswing_of_racket"], Literal["left_hand"], Literal["right_hand"],
Literal["left_leg"], Literal["right_leg"], Literal["left_knee"], Literal["right_knee"],
Literal["right_finger"], Literal["upper_body"],
Literal['grip_of_racket'], Literal['others']]

allowed_sugg_keys = ['center_of_gravity', 'right_wrist', 'right_shoulder', 'right_forearm', 'time_of_striking_ball',
                     'angle_of_racket', 'left_foot', 'right_foot', 'waist', 'right_upper_arm', 'left_shoulder',
                     'left_elbow', 'right_elbow', 'left_wrist', 'backswing_of_racket', 'left_hand', 'right_hand',
                     'left_leg', 'right_leg', 'left_knee', 'right_knee', 'right_finger', 'upper_body', 'grip_of_racket',
                     'others']

AllowedDataFeatureKeys = Union[
     Literal["nose"], Literal["left_eye_inner"], Literal["left_eye"], Literal[
        "left_eye_outer"], Literal["right_eye_inner"], Literal["right_eye"], Literal["right_eye_outer"], Literal[
        "left_ear"], Literal["right_ear"], Literal["mouth_left"], Literal["mouth_right"], Literal["left_shoulder"],
    Literal["right_shoulder"], Literal["left_elbow"], Literal["right_elbow"],
    Literal["left_wrist"], Literal["right_wrist"], Literal["left_pinky"], Literal["right_pinky"], Literal["left_index"],
    Literal["right_index"], Literal["left_thumb"], Literal["right_thumb"],
    Literal["left_hip"], Literal["right_hip"], Literal["left_knee"], Literal["right_knee"], Literal["left_ankle"],
    Literal["right_ankle"], Literal["left_heel"], Literal["right_heel"],
    Literal["left_foot_index"], Literal["right_foot_index"],

Literal["acc_peak_exp_sqrt"], Literal["agl_y_peak"], Literal["agl_spd_peak_exp_sqrt"],

Literal["acc_x"],    Literal["acc_y"],    Literal["acc_z"],
    Literal["agl_speed_x"],    Literal["agl_speed_y"],    Literal["agl_speed_z"],
    Literal["agl_x"],    Literal["agl_y"],    Literal["agl_z"],
    Literal["mgt_x"],    Literal["mgt_y"],    Literal["mgt_z"],
    Literal["quat_1"],    Literal["quat_2"],    Literal["quat_3"],    Literal["quat_4"]
]

# region Raw text key to SuggKeys
clean_key_mapping: Dict[str, AllowedSuggestionKey] = {
    "nose": "others",
    "chest": "right_shoulder",
    "shoulder": "right_shoulder",
    "shoulders": "right_shoulder",
    "left_shoulder": "left_shoulder",
    "left shoulder": "left_shoulder",
    "right_shoulder": "right_shoulder",
    "right shoulder": "right_shoulder",
    "right shoulder and right shoulder joint": "right_shoulder",
    "shoulders and arms": "left_shoulder",
    "shoulder blades": "right_shoulder",
    "shoulder and waist/abdomen": "right_shoulder",
    "shoulder and upper arm": "right_shoulder",
    "left_wrist": "left_wrist",
    "left wrist": "left_wrist",
    "right_wrist": "right_wrist",
    "right wrist": "right_wrist",
    "right wrist and right forearm": "right_wrist",
    "right wrist and fingers": "right_wrist",
    "right hand": "right_wrist",
    "hand": "right_wrist",
    "left_hand": "left_hand",
    "left hand": "left_hand",
    "right_fingers": "right_finger",
    "right fingers": "right_finger",
    "right middle finger, right ring finger, right pinky": "right_finger",
    "right index": "right_finger",
    "right index finger": "right_finger",
    "right index finger belly": "right_finger",
    "right index fingertip": "right_finger",
    "back of hand": "right_hand",
    "arms": "right_forearm",
    "arm": "right_forearm",
    "forearm": "right_forearm",
    "right forearm": "right_forearm",
    "left forearm": "left_wrist",
    "forearm and back of hand": "right_forearm",
    "forearm and wrist": "right_forearm",
    "right elbow": "right_elbow",
    "right elbow and wrist": "right_elbow",
    "right elbow and right shoulder": "right_elbow",
    "right elbow and shoulder": "right_elbow",
    "left_elbow": "left_elbow",
    "left elbow": "left_elbow",
    "elbow": "right_elbow",
    "left_knee": "left_knee",
    "left knee": "left_knee",
    "right_knee": "right_knee",
    "right knee": "right_knee",
    "right knee, left knee": "right_knee",
    "knees": "right_knee",
    "left_leg": "left_leg",
    "left leg": "left_leg",
    "right_leg": "right_leg",
    "right leg": "right_leg",
    "right leg and right knee": "right_leg",
    "right leg, left leg": "right_leg",
    "upper body": "upper_body",
    "center of gravity": "center_of_gravity",
    "center of gravity of upper body": "center_of_gravity",
    "upper body center of gravity": "center_of_gravity",
    "head": "others",
    "foot": "right_foot",
    "feet": "right_foot",
    "both feet": "right_foot",
    "right_foot": "right_foot",
    "right foot": "right_foot",
    "left foot_index": "left_foot",
    "left foot": "left_foot",
    "right_foot_index": "right_foot",
    "footwork": "others",
    "core": "others",
    "hip": "others",
    "right hip": "others",
    "friction": "others",
    "lower body": "upper_body",
    "stance": "others",
    "general movement": "others",
    "force exertion": "others",
    "effort": "others",
    "distance of shot": "others",
    "distance between body and racket": "others",
    "between the shoulder blades and body": "others",
    "gripping method": "grip_of_racket",
    "grip of racket": "grip_of_racket",
    "gripping hand": "grip_of_racket",
    "grip": "grip_of_racket",
    "right hand grip": "grip_of_racket",
    "center of gravity of lower body": "upper_body",
    "legs": "right_leg",
    "right middle finger": "right_finger",
    "right ring finger": "right_finger",
    "right pinky": "right_finger",
    "right wrist, right forearm": "right_wrist",
    "right upper arm": "right_upper_arm",
    "right upper arm, upper body": "upper_body",
    "right upper arm and right shoulder": "right_upper_arm",
    "upper and lower body": "center_of_gravity",
    "right shoulder and right upper arm": "right_shoulder",
    "right shoulder, chest, waist": "right_shoulder",
    "right shoulder, right elbow, right wrist": "right_shoulder",
    "left wrist and right wrist": "right_wrist",
    "waist": "waist",
    "right waist": "right_wrist",
    "right shoulder and right wrist": "right_shoulder",
    "right shoulder and waist": "right_shoulder",
    "right forearm and shoulder": "right_forearm",
    "left elbow and shoulder": "left_shoulder",
    "shoulder, waist, hips": "right_shoulder",
    "right shoulder, right upper arm, right forearm": "right_shoulder",
    "waist and right forearm": "waist",
    "waist, hips, shoulders": "waist",
    "waist, shoulder": "waist",
    "waist, right hand": "waist",
    "waist and legs": "waist",
    "waist and shoulder": "waist",
    "waist and shoulders": "waist",
    "waist and hips": "waist",
    "waist and right hip": "waist",
    "waist and shoulder angle": "waist",
    "knee": "right_knee",
    "the whole body": "center_of_gravity",
    "the whole arm": "right_elbow",
    "main joint": "right_elbow",
    "backswing of racket": "backswing_of_racket",
    "angle of racket": "angle_of_racket",
    "position of racket": "others",
    "hand on racket": "right_hand",
    "right wrist on racket": "right_hand",
    "racket grip": "grip_of_racket",
    "racket angle": "angle_of_racket",
    "hands and backswing": "backswing_of_racket",
    "right hand fingers": "right_hand",
    "racket angle and position": "angle_of_racket",
    "distance to racket": "others",
    "way to grip racket": "grip_of_racket",
    "grip the racket": "grip_of_racket",
    "others": "others"
}

suggKey_to_dataKey_mapping: Dict[AllowedSuggestionKey, List[AllowedDataFeatureKeys]] = {
    "center_of_gravity": ["left_hip", "right_hip", "left_shoulder", "right_shoulder"],
    "right_wrist": ["right_wrist"],
    "right_shoulder": ["right_shoulder"],
    "right_forearm": ["right_elbow", "right_wrist"],
    "time_of_striking_ball": ["acc_x", "acc_y", "acc_z", "agl_speed_x", "agl_speed_y", "agl_speed_z"],
    "angle_of_racket": ["agl_x", "agl_y", "agl_z"],
    "left_foot": ["left_foot_index", "left_ankle", "left_heel"],
    "right_foot": ["right_foot_index", "right_ankle", "right_heel"],
    "waist": ["left_hip", "right_hip"],
    "right_upper_arm": ["right_shoulder"],
    "left_shoulder": ["left_shoulder"],
    "left_elbow": ["left_elbow"],
    "right_elbow": ["right_elbow"],
    "left_wrist": ["left_wrist"],
    "backswing_of_racket": ["right_shoulder", "right_wrist", "agl_speed_x", "agl_speed_y", "agl_speed_z"],
    "left_hand": ["left_wrist", "left_index", "left_pinky", "left_thumb"],  # mapped to actual hand part
    "right_hand": ["right_wrist", "right_index", "right_pinky", "right_thumb"],  # mapped to actual hand part
    "left_leg": ["left_knee"],  # mapped to an allowable key
    "right_leg": ["right_knee"],  # mapped to an allowable key
    "left_knee": ["left_knee"],
    "right_knee": ["right_knee"],
    "right_finger": ["right_index", "right_pinky", "right_thumb"],
    "upper_body": ["left_shoulder", "right_shoulder"],
    "grip_of_racket": ["right_wrist", "right_index", "right_pinky", "right_thumb"],
    "others": []
}
suggKey_to_dataKey_aggregated_mapping: Dict[AllowedSuggestionKey, List[AllowedDataFeatureKeys]] = {
    "center_of_gravity": ["left_hip", "right_hip", "left_shoulder", "right_shoulder"],
    "right_wrist": ["right_wrist"],
    "right_shoulder": ["right_shoulder"],
    "right_forearm": ["right_elbow", "right_wrist"],
    "time_of_striking_ball": ["agl_spd_peak_exp_sqrt", "acc_peak_exp_sqrt"],
    "angle_of_racket": ["agl_y_peak"],
    "left_foot": ["left_foot_index", "left_ankle", "left_heel"],
    "right_foot": ["right_foot_index", "right_ankle", "right_heel"],
    "waist": ["left_hip", "right_hip"],
    "right_upper_arm": ["right_shoulder"],
    "left_shoulder": ["left_shoulder"],
    "left_elbow": ["left_elbow"],
    "right_elbow": ["right_elbow"],
    "left_wrist": ["left_wrist"],
    "backswing_of_racket": ["right_shoulder", "right_wrist", "agl_spd_peak_exp_sqrt"],
    "left_hand": ["left_wrist", "left_index", "left_pinky", "left_thumb"],  # mapped to actual hand part
    "right_hand": ["right_wrist", "right_index", "right_pinky", "right_thumb"],  # mapped to actual hand part
    "left_leg": ["left_knee"],  # mapped to an allowable key
    "right_leg": ["right_knee"],  # mapped to an allowable key
    "left_knee": ["left_knee"],
    "right_knee": ["right_knee"],
    "right_finger": ["right_index", "right_pinky", "right_thumb"],
    "upper_body": ["left_shoulder", "right_shoulder"],
    "grip_of_racket": ["right_wrist", "right_index", "right_pinky", "right_thumb"],
    "others": []
}
